# Generated by Django 5.1.1 on 2024-10-04 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='major',
            field=models.CharField(default=' ', max_length=100, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='register',
            name='college',
            field=models.CharField(max_length=100, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='register',
            name='student_number',
            field=models.CharField(max_length=100, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='register',
            name='university',
            field=models.CharField(max_length=100, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='register',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
