# Generated by Django 5.1.1 on 2024-10-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_register_major_alter_register_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='major',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='专业'),
        ),
    ]
