# Generated by Django 5.1.1 on 2024-10-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_goal',
            field=models.CharField(blank=True, default='暂无', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_need',
            field=models.CharField(blank=True, default='暂无', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_num',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default='暂无', max_length=100, null=True),
        ),
    ]
