# Generated by Django 5.1.1 on 2024-10-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_description_alter_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_end',
            field=models.DateField(blank=True, null=True, verbose_name='项目截止日期'),
        ),
    ]
